typography_spectrum: 0.77766
color:
  brandColors:
    - '#ffffff'
    - '#131610'
    - '#887668'
    - '#334b2a'
    - '#d3cfcf'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.88299
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/66022dd6-c96c-4a81-9fe8-78ed7c2a2e4b.png
name: Raconteur Studios
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1de9756d-bef0-4c54-ba5b-ee5891b25fac.png
title: Raconteur Studios
purpose: []
