name: Raconteur Sound
favicon: null
layout_spectrum: 1
typography_spectrum: 0.77282
title: Raconteur Sound
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b090a'
    - '#6995c4'
    - '#edf1f9'
    - '#2d292a'
    - '#a79d8d'
  brandStrength: 0.9378895964473486
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.7469736377242953
purpose: []
