name: Raconteur Sound
favicon: null
layout_spectrum: 0.64701
typography_spectrum: 0.7738
title: Raconteur Sound
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b090a'
    - '#6995c4'
    - '#edf1f9'
    - '#2d292a'
    - '#a79d8d'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
